Update train.yaml
remove conda init step and see if it does any change

diff --git a/.github/workflows/train.yaml b/.github/workflows/train.yaml
--- a/.github/workflows/train.yaml
+++ b/.github/workflows/train.yaml
@@ -17,23 +17,16 @@ jobs:
       #   with:
       #     python-version: '3.x'
       - uses: iterative/setup-cml@v2
-      # - name: install_aws_cli
-      #   run: |
-      #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-      #     apt-get install zip unzip
-      #     unzip awscliv2.zip
-      #     apt-get install sudo
-      #     sudo ./aws/install
       - name: configure_aws_credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-2
-      - name: Initialize Conda
-        run: |
-          conda init bash
-          /bin/bash -c "source ~/.bashrc" || echo "Error sourcing bashrc"
+      # - name: Initialize Conda
+      #   run: |
+      #     conda init bash
+      #     /bin/bash -c "source ~/.bashrc" || echo "Error sourcing bashrc"
       - name: Debug Environment
         run: |
           echo "Current Shell: $SHELL"
